### ISSUE TITLE
Last update buggy on Python 2.7?

### ISSUE THREAD

**Issue by bluescarni** [conda-forge/cloudpickle-feedstock#17]
It seems like the latest update to cloudpickle (0.4.2) has a bug on Python 2.7, that was exposed in our CI pipeline.

For starters, here's a successful build from a few days ago using cloudpickle 0.4.0 (you can check the version from the output of ``conda install`` at the beginning of the log):

https://travis-ci.org/esa/pagmo2/jobs/321180854#L2113

After the update to cloudpickle 0.4.2, our Python 2.7 build started to fail:

https://travis-ci.org/esa/pagmo2/jobs/322496051#L1369

Our Python 3.6 build however happily kept chugging along:

https://travis-ci.org/esa/pagmo2/jobs/322496050#L1353

In order to confirm that the cloudpickle update from 0.4.0 to 0.4.2 is the likely culprit, I did a small change in our travis script to install cloudpickle via ``pip`` rather than from the conda package. This pulled in the latest cloudpickle version, 0.5.2, and led to a successful build on Python 2.7:

https://travis-ci.org/esa/pagmo2/jobs/322580855#L1373

Would it be possible to get an update to 0.5.2 in the conda package?

**Comment by jakirkham** [comment]
Sure. A PR for the update would be welcome.

**Comment by jakirkham** [comment]
Updating in PR ( https://github.com/conda-forge/cloudpickle-feedstock/pull/18 ).

**Comment by jakirkham** [comment]
The `cloudpickle` version `0.5.2` package is released.

**Comment by bluescarni** [comment]
@jakirkham Thanks a lot! I'll test it on our CI and let you know how it goes.

**Comment by jakirkham** [comment]
np. If there are more issues, they may be with `cloudpickle` itself. Would be good to create an MRE and raise it with `cloudpickle` should issues persist in the latest release.

**Comment by bluescarni** [comment]
@jakirkham Builds are good:

https://travis-ci.org/esa/pagmo2/jobs/323127430#L2126

I meant originally to raise the issue with the ``cloudpickle`` folks, but then it looked like the problem was already fixed in the latest release so I came bothering you instead :)

Thanks again for the update.
